baseURL = "http://rpi-data.analyticsdojo.com/"
languageCode = "en-us"
title = "Data@Rensselaer"
theme = "docdock"
publishDir = "docs"
[params]
#disableHomeIcon = true
pygmentsCodeFences = false
pygmentsStyle = "monokailight"
noSearch = false # default is false
showVisitedLinks = false # default is false
menushortcutsnewtab = true # Opens links in new tabs
# themeStyle = "theme" # overide base css
#themeVariant = "gray" # choose theme variant "green", "gold" , "gray", "blue" (default)
#ordersectionsby = "weight" # ordersectionsby = "title"
github_org="rpi-data"
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params.widgets]
    search = true
    categories = true
    tags = true
	
[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> <label>Github</label>"
identifier = "ds"
url = "https://github.com/rpi-data/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-cloud-download'></i> <label>Colab</label>"
url = "https://colab.research.google.com/"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-slack'></i> <label>Slack</label>"
identifier = "slack"
url = "https://join.slack.com/t/rpi-data/signup"
weight = 20

#[[menu.shortcuts]]
#name = "<i class='fa fa-bullhorn'></i> <label>Credits</label>"
#url = "/credits"
#weight = 30
